name: jamal_car_buying_experience
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^2.0.1
  video_player: ^2.4.10
  visibility_detector: ^0.3.3
  fluentui_system_icons: ^1.1.189
  flutter_svg: ^1.1.6

flutter_gen:
  integrations:
    flutter_svg: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    
  fonts:
    - family: FuturaNowHeadline
      fonts:
        - asset: assets/fonts/FuturaNowHeadlineExtraBlack.ttf

    - family: watchmen
      fonts:
        - asset: assets/fonts/watchmen.ttf
   
